### ISSUE TITLE
The app Crash when open V3.10 - beta1

### ISSUE THREAD

**Issue by xmithosx** [OpenNingia/l5r-character-manager-3#290]
Hello, after install and with only the core datapack (embedded), te app try to open and then close (like a flash), i try the solution of another similar issue and don't work, i'm running Win 8.1

**Comment by xmithosx** [comment]
Report error in LOG:

2015-09-23 19:27:46,338 app          INFO     l5rcm base dir: C:\Program Files\openningia\l5rcm
2015-09-23 19:27:46,355 app          INFO     START
2015-09-23 19:27:46,457 app          INFO     l5rcm 3.10.0 Legend of the Five Rings: Character Manager by openningia
2015-09-23 19:27:46,457 app          DEBUG    use machine locale: yes, machine locale: es_ES
2015-09-23 19:27:46,457 app          DEBUG    current locale: es_ES, qt locale: qt_es, app locale file: C:\Program Files\openningia\l5rcm\share/l5rcm\i18n/es_ES
2015-09-23 19:27:46,457 app          DEBUG    qt translation path: C:\Qt\4.8.7\translations
2015-09-23 19:27:46,459 ui           DEBUG    Initialize L5RMain window
2015-09-23 19:27:46,460 ui           DEBUG    Build L5RMain UI
2015-09-23 19:27:46,463 ui           DEBUG    background color: #000000
2015-09-23 19:27:46,471 ui           DEBUG    show banner: no
2015-09-23 19:27:46,473 ui           INFO     restore geometry from settings
2015-09-23 19:27:46,473 rules        INFO     insight calculator settings: 1/3
2015-09-23 19:27:46,614 api          INFO     Created new character
2015-09-23 19:27:46,624 app          ERROR    'ascii' codec can't encode character u'\xed' in position 2: ordinal not in range(128)
Traceback (most recent call last):
  File "main.py", line 2625, in main
  File "main.py", line 2538, in create_new_character
  File "sinks\sink_1.pyc", line 50, in new_character
  File "main.py", line 2148, in update_from_model
  File "main.py", line 2227, in update_wound_penalties
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 2: ordinal not in range(128)
