### ISSUE TITLE
PDF generation silently fail if target file is opened by another process

### ISSUE THREAD

**Issue by OpenNingia** [OpenNingia/l5r-character-manager-3#306]
Traceback (most recent call last):
  File "sinks\sink_1.pyc", line 86, in export_character_as_pdf
  File "l5rcmcore__init__.pyc", line 310, in export_as_pdf
  File "l5rcmcore__init__.pyc", line 230, in commit_pdf_export
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:/Users/cns_dasi/Documents/L5RCM/Hosaru.pdf'

We should trap this error and show an error message to the user.

**Comment by OpenNingia** [comment]
Added an alert in case of failure (v3.14)
