### ISSUE TITLE
Error exporting PDF

### ISSUE THREAD

**Issue by Orifiel** [OpenNingia/l5r-character-manager-3#329]
I can normally create a character and generate the file using the "save as".

However when trying to export the pdf, present the following error (via terminal)

Traceback (most recent call last):
  File "/home/cleiton/l5r-character-manager-3/l5r/sinks/sink_1.py", line 86, in export_character_as_pdf
    form.export_as_pdf (file_)
  File "/home/cleiton/l5r-character-manager-3/l5r/l5rcmcore/__init__.py", line 259, in export_as_pdf
    self.flatten_pdf (source_fdf, source_pdf, fpath)
  File "/home/cleiton/l5r-character-manager-3/l5r/l5rcmcore/__init__.py", line 188, in flatten_pdf
    subprocess.call (args_)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen (* popenargs, ** kwargs) .wait ()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] nonexistent file or directory

PLZ HELP ME

**Comment by Orifiel** [comment]
Consegui resolver. 

O problema esta que o pacote PDFTK já não faz referencia com esse nome e sim como PDFTK-JAVA, e o L5RCM entende apenas o PDFTK. 

Assim desinstalei a versão pdftk-java e instalei a versão anterior pdftk. 

funcionou!
